server: 
  port: 9527
 
spring: 
  application:
    name: weiqimsc-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: zuul-gateway
    prefer-ip-address: true 
    
zuul: 
  #ignored-services: weiqimsc-consumer
  prefix: /weiqi
  ignored-services: "*"#隐藏所有工程名
  routes: 
    mydept.serviceId: weiqimsc-consumer
    mydept.path: /mydept/**
 
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: false
#    
#host:
#  socket-timeout-millis: 12000
#  connect-timeout-millis: 12000

info: 
  app.name: weiqimsc-zuul-gateway
  company.name: www.dingshuapay.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$