server:
  port: 8011
  
spring:
  application:
    name: weiqimsc-consumer
  zipkin:
    base-url: http://127.0.0.1:9107
  sleuth:
    sampler.percentage: 1
  
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: weiqimsc-consumer
    prefer-ip-address: true  
    
feign: 
  hystrix: 
    enabled: true
    
info: 
  app.name: weiqimsc-consumer
  company.name: www.dingshuapay.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$